### ISSUE TITLE
TemporaryDirectory delete option vs python version

### ISSUE THREAD

**Issue by sdx23** [suuuehgi/noteshrunk#3]
TemporaryDirectory does not have a "delete" option in python 3.11. Possibly it was introduced only in 3.12, but I'm unsure since docs are silent about it. Thus, execution of noteshrunk fails with
```
Traceback (most recent call last):
  File "/home/user/.local/bin/noteshrunk", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/user/.local/pipx/venvs/noteshrunk/lib/python3.11/site-packages/src/noteshrunk.py", line 900, in main
    with tempfile.TemporaryDirectory(dir=os.getcwd(), prefix='tmp_pdfs-', delete=(not args.keep_intermediate)) as temp_dir:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: TemporaryDirectory.__init__() got an unexpected keyword argument 'delete'

```

So, either pyproject should require a sufficient python version, or - perferably - the code should be fixed to make noteshrunk work with older python versions as well. Maybe just get rid of keep_intermediate. If that's not acceptable, possibly something like this (warning message optional):
```
def create_temp_dir(base_dir, prefix, keep_intermediate):
    try:
        return tempfile.TemporaryDirectory(
            dir=base_dir,
            prefix=prefix,
            delete=(not keep_intermediate)
        )
    except TypeError:
        return tempfile.TemporaryDirectory(
            dir=base_dir,
            prefix=prefix
        )

with create_temp_dir(
    base_dir=os.getcwd(),
    prefix='tmp_pdfs-',
    keep_intermediate=args.keep_intermediate
) as tmp_dir:
```

**Comment by suuuehgi** [comment]
Done 🙏
